love_song:
  fields: {}
  target:
    entity:
      domain: media_player
      integration: pianobar

ban_song:
  fields: {}
  target:
    entity:
      domain: media_player
      integration: pianobar

tired_of_song:
  fields: {}
  target:
    entity:
      domain: media_player
      integration: pianobar

create_station:
  fields:
    type:
      required: false
      default: "song"
      selector:
        select:
          options:
            - "song"
            - "artist"
  target:
    entity:
      domain: media_player
      integration: pianobar

rename_station:
  fields:
    station_id:
      required: true
      selector:
        text:
    name:
      required: true
      selector:
        text:
  target:
    entity:
      domain: media_player
      integration: pianobar

delete_station:
  fields:
    station_id:
      required: true
      selector:
        text:
  target:
    entity:
      domain: media_player
      integration: pianobar

reconnect:
  fields: {}
  target:
    entity:
      domain: media_player
      integration: pianobar

explain_song:
  fields: {}
  target:
    entity:
      domain: media_player
      integration: pianobar

get_upcoming:
  fields: {}
  target:
    entity:
      domain: media_player
      integration: pianobar

set_quick_mix:
  fields:
    station_ids:
      required: true
      selector:
        object:
  target:
    entity:
      domain: media_player
      integration: pianobar

add_seed:
  fields:
    music_id:
      required: true
      selector:
        text:
    station_id:
      required: true
      selector:
        text:
  target:
    entity:
      domain: media_player
      integration: pianobar

get_station_info:
  fields:
    station_id:
      required: true
      selector:
        text:
  target:
    entity:
      domain: media_player
      integration: pianobar

delete_seed:
  fields:
    seed_id:
      required: true
      selector:
        text:
    seed_type:
      required: true
      selector:
        select:
          options:
            - "artist"
            - "song"
            - "station"
    station_id:
      required: true
      selector:
        text:
  target:
    entity:
      domain: media_player
      integration: pianobar

delete_feedback:
  fields:
    feedback_id:
      required: true
      selector:
        text:
    station_id:
      required: true
      selector:
        text:
  target:
    entity:
      domain: media_player
      integration: pianobar

get_station_modes:
  fields:
    station_id:
      required: true
      selector:
        text:
  target:
    entity:
      domain: media_player
      integration: pianobar

set_station_mode:
  fields:
    station_id:
      required: true
      selector:
        text:
    mode_id:
      required: true
      selector:
        number:
          min: 0
          max: 3
          mode: slider
  target:
    entity:
      domain: media_player
      integration: pianobar

toggle_playback:
  fields: {}
  target:
    entity:
      domain: media_player
      integration: pianobar

reset_volume:
  fields: {}
  target:
    entity:
      domain: media_player
      integration: pianobar

search:
  fields:
    query:
      required: true
      selector:
        text:
  target:
    entity:
      domain: media_player
      integration: pianobar

get_genres:
  fields: {}
  target:
    entity:
      domain: media_player
      integration: pianobar

create_station_from_music_id:
  fields:
    music_id:
      required: true
      selector:
        text:
  target:
    entity:
      domain: media_player
      integration: pianobar

add_shared_station:
  fields:
    station_id:
      required: true
      selector:
        text:
  target:
    entity:
      domain: media_player
      integration: pianobar

switch_account:
  fields:
    account_id:
      required: true
      selector:
        text:
  target:
    entity:
      domain: media_player
      integration: pianobar
